# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [Environment]::SetEnvironmentVariable("Environment", "value")
      [Environment]::GetEnvironmentVariables()
      [Environment]::GetEnvironmentVariable("SYSTEM_JOBID")
      [Environment]::GetEnvironmentVariable("Environment")
      
    failOnStderr: true
    showWarnings: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |

      [Environment]::GetEnvironmentVariable("Environment")
      "by user"
      [Environment]::GetEnvironmentVariable("Environment" , [System.EnvironmentVariableTarget]::User)
     
      
    failOnStderr: true
    showWarnings: true