# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
      [Environment]::GetEnvironmentVariable("buildConfiguration", "User")
      [Environment]::GetEnvironmentVariable("buildConfiguration")

      
      [Environment]::SetEnvironmentVariable("SAUCE_USERNAME", "hahah", "User")
      "firsttry"
      $val = [Environment]::GetEnvironmentVariable("SAUCE_USERNAME", "User")
      $val
      [Environment]::SetEnvironmentVariable("Environment", "MyValue", [System.EnvironmentVariableTarget]::User)      
            
              "split line"
                  [Environment]::GetEnvironmentVariable("Environment")
                  "try machine"
                  
      [Environment]::SetEnvironmentVariable("Environment", "MyValue2", [System.EnvironmentVariableTarget]::Machine)  
        
                  [Environment]::GetEnvironmentVariable("Environment")